ALTER TABLE tblTPopKontr DROP INDEX TPopKontrZaehleinheit1;
ALTER TABLE tblTPopKontr DROP INDEX TPopKontrMethode1;
ALTER TABLE tblTPopKontr DROP INDEX TPopKontrZaehleinheit2;
ALTER TABLE tblTPopKontr DROP INDEX TPopKontrMethode2;
ALTER TABLE tblTPopKontr DROP INDEX TPopKontrZaehleinheit3;
ALTER TABLE tblTPopKontr DROP INDEX TPopKontrMethode3;
ALTER TABLE tblTPopKontr DROP TPopKontrZaehleinheit1;
ALTER TABLE tblTPopKontr DROP TPopKontrMethode1;
ALTER TABLE tblTPopKontr DROP TPopKontrAnz1;
ALTER TABLE tblTPopKontr DROP TPopKontrZaehleinheit2;
ALTER TABLE tblTPopKontr DROP TPopKontrMethode2;
ALTER TABLE tblTPopKontr DROP TPopKontrAnz2;
ALTER TABLE tblTPopKontr DROP TPopKontrZaehleinheit3;
ALTER TABLE tblTPopKontr DROP TPopKontrMethode3;
ALTER TABLE tblTPopKontr DROP TPopKontrAnz3;