select COLUMN_NAME,  DATA_TYPE, IS_NULLABLE, CHARACTER_MAXIMUM_LENGTH, NUMERIC_PRECISION, COLUMN_COMMENT from INFORMATION_SCHEMA.COLUMNS where table_name='tblTeilpopulation'

select * from INFORMATION_SCHEMA.COLUMNS where table_name='tblTeilpopulation'



select INFORMATION_SCHEMA.COLUMNS.COLUMN_NAME,  INFORMATION_SCHEMA.COLUMNS.DATA_TYPE, INFORMATION_SCHEMA.COLUMNS.IS_NULLABLE, INFORMATION_SCHEMA.COLUMNS.CHARACTER_MAXIMUM_LENGTH, INFORMATION_SCHEMA.COLUMNS.NUMERIC_PRECISION, INFORMATION_SCHEMA.COLUMNS.COLUMN_COMMENT from INFORMATION_SCHEMA.COLUMNS where table_name IN (SELECT TABLE_NAME FROM `TABLES` WHERE `TABLE_SCHEMA`='alexande_apflora')

select * from INFORMATION_SCHEMA.COLUMNS where table_name IN (SELECT TABLE_NAME FROM `TABLES` WHERE `TABLE_SCHEMA`='alexande_apflora')



select INFORMATION_SCHEMA.TABLES.TABLE_NAME, INFORMATION_SCHEMA.TABLES.TABLE_ROWS, INFORMATION_SCHEMA.TABLES.TABLE_COMMENT, INFORMATION_SCHEMA.COLUMNS.COLUMN_NAME,  INFORMATION_SCHEMA.COLUMNS.DATA_TYPE, INFORMATION_SCHEMA.COLUMNS.IS_NULLABLE, INFORMATION_SCHEMA.COLUMNS.CHARACTER_MAXIMUM_LENGTH, INFORMATION_SCHEMA.COLUMNS.NUMERIC_PRECISION, INFORMATION_SCHEMA.COLUMNS.COLUMN_COMMENT from INFORMATION_SCHEMA.COLUMNS INNER JOIN INFORMATION_SCHEMA.TABLES ON INFORMATION_SCHEMA.TABLES.TABLE_NAME = INFORMATION_SCHEMA.COLUMNS.TABLE_NAME where INFORMATION_SCHEMA.COLUMNS.TABLE_NAME IN (SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='alexande_apflora')




SELECT TABLE_NAME, TABLE_ROWS, TABLE_COLLATION, TABLE_COMMENT FROM `TABLES` WHERE `TABLE_SCHEMA`='alexande_apflora'